### PR TITLE
Added the AboutUs.html and some images

### PR DESCRIPTION
**Pull request by hritika2409**
resolve issue: #issue_number  #32
Checklist: ☑️

- [x]  My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly wherever it was hard to understand.
- [x]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [x]  I have added things that prove my fix is effective or that my feature works.
- [x]  Any dependent changes have been merged and published in downstream modules.

How Has This Been Tested? ⚙️
Describe how have you verified the changes made.

@XceeDesigns I have added an About page which matches the overall website's theme and color combinations.I even made changed in all pages and added the option of About Us.Please review the changes and do tell me if you need any change or else kindly merge the PR.
Thank You!

https://github.com/XceeDesigns/Website/assets/117531823/07df79f3-5f23-401e-8384-0eb2dfafdd39

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Fix these issues:

1. Change the image and align it with the theme.
image

2. Change the design of the cards and remove the whitespace below the cards section.
Screenshot 2024-05-24 150834

@hritika2409

**Comment by hritika2409** [comment]
https://github.com/XceeDesigns/Website/assets/117531823/3e79d4db-6a89-456e-b826-f6626c95509d

I have made the changes as you asked,Is it fine now or do you need any other change? @XceeDesigns

**Comment by ParthMadhvani2** [comment]
@hritika2409 Change the design of the cards

**Comment by hritika2409** [comment]
hey @ParthMadhvani2 should i change it now?

**Pull request closed without merging**
