### PR TITLE
[Enhancement] Footer

### LINKED ISSUE #94: Enhanc: add animations to the footer
Screenshot 2024-05-19 184845

Add animations here
N.B: I am a GSSOC contributor

### PR DESCRIPTION
**Pull request by sau-mili**
1. Added SVG animated background
2. Added animation on the information
3. Modified the footer text for better UI
Fixes #94

https://github.com/XceeDesigns/Website/assets/146661411/5720ce26-a082-496b-9ad4-db3026764aaa

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Not aligning with our theme

**Comment by sau-mili** [comment]
Should I change the svg with sharper peaked ones? Or remove it completely?

**Comment by XceeDesigns** [comment]
@sau-mili As you know, our website focuses on professionalism, and your design leans towards a funky style. Please either change it to a more subtle design or remove it.

**Comment by sau-mili** [comment]
https://github.com/XceeDesigns/Website/assets/146661411/ac191151-8f49-4831-b1e0-5bab55443faa

Does this look okay?

**Pull request closed without merging**
