### PR TITLE
Loader added when submitting contact form

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
Loader added when submitting contact form

https://github.com/XceeDesigns/Website/assets/125277258/a4f14677-9165-4430-bdcf-7f90b07a6fdd

issue #128 solved

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Change loading gif try using gif without background and make entire screen slightly blur when loading occurs

**Comment by RamakrushnaBiswal** [comment]
Ok

**Comment by RamakrushnaBiswal** [comment]
https://github.com/XceeDesigns/Website/assets/125277258/56941eb2-4809-459e-9ca3-dc39c85dc1c3

**Comment by XceeDesigns** [comment]
@RamakrushnaBiswal merging your PR but would request you to adjust loading screen for various screens and you can raise a seprate issue/PR for that

**Pull request merged**
