### PR TITLE
added comments

### PR DESCRIPTION
**Pull request by sakshii00**
comments have been added in all the files.
for issue #22 

please review and merge it

### CODE REVIEW

**Comment by XceeDesigns** [comment]
@sakshii00 Kindly first pull the repo before working on any issue to ensure that you are working on updated code.
Would request you to review the code again after syncing and pulling the repo.

**Comment by sakshii00** [comment]
I synced the fork and the files I had changed didn't have any changes till then so the code should be fine, I did review it but please cross check it and let me know if something else is required. Thank you!

**Review by Apurv7777 — COMMENTED** [review]
Is these comments really required ?

**Comment by XceeDesigns** [comment]
@sakshii00 Kindly resolve merge conflict any let me know after that we will merge your PR.

**Comment by sakshii00** [comment]
I've resolved the merge conflict, sorry if that caused any trouble. Let me know if there is something else that is required!

**Comment by XceeDesigns** [comment]
Hii @sakshii00 
PR is still having some conflicts, do resolve them.
image

**Comment by sakshii00** [comment]
I resolved them.

**Pull request merged**
