### PR TITLE
added about-us-page

### LINKED ISSUE #32: About-Us page can be added
An about-us page can be added which will include about the website `XceeDesigns` like, Introduction, Story, etc

@XceeDesigns Can i work on this issue under GSSoC'24. I would love to work on this addition.
Thank You!

### PR DESCRIPTION
**Pull request by AtharvKasar04**
Resolves #32 

@XceeDesigns I have added an About page which matches the overall website's theme and color combinations.
Please review the changes and kindly merge the PR.
Thank You!

## I've added a Screenshot below:
image

### CODE REVIEW

**Comment by XceeDesigns** [comment]
@AtharvKasar04 Thanks for your contibution i would request you to add about section in dashboard page as well.

P.S. Click of logo of XceeDesigns on navbar to access Dashboard.

File changes required in contact-dashboard.html

**Comment by AtharvKasar04** [comment]
> @AtharvKasar04 Thanks for your contibution i would request you to add about section in dashboard page as well.
> 
> P.S. Click of logo of XceeDesigns on navbar to access Dashboard.
> 
> File changes required in contact-dashboard.html

Yes sure, I will do that.

**Comment by XceeDesigns** [comment]
Hii @AtharvKasar04 ,
We praise and understand your hardwork, but our inhouse developer thoughts are different on this.
According to them service and about page is 99% similar thus create a sense of redundancy.

We request either make recognisable changes in about us page or just change first image of services page with first image of about us page.

P.S. : We will merge your PR just for changing image in services page and removing about us page under GSSOC with level3 tag.

Hope you understand our concern.
Happy Coding!

**Comment by AtharvKasar04** [comment]
> Hii @AtharvKasar04 , We praise and understand your hardwork, but our inhouse developer thoughts are different on this. According to them service and about page is 99% similar thus create a sense of redundancy.
> 
> We request either make recognisable changes in about us page or just change first image of services page with first image of about us page.
> 
> P.S. : We will merge your PR just for changing image in services page and removing about us page under GSSOC with level3 tag.
> 
> Hope you understand our concern. Happy Coding!

@XceeDesigns 
Apologies for the designing issues, so what will be the new tag for this issue or should i make a new issue for any other issue!

**Comment by XceeDesigns** [comment]
You can work with this same issue or can raise a new issue for changing image of services page.

**Pull request closed without merging**
