### PR TITLE
added hover effect for the icons in the website

### LINKED ISSUE #93: Feat: Adding hovering effect to the icons
### Describe the feature

I want to add the hovering effect to the icons 
I am looking forward to contribute to this issue 

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by reshamsai150**
closes #93
image

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Animation is not smooth

**Comment by reshamsai150** [comment]
I will make changes

**Comment by reshamsai150** [comment]
made some changes @XceeDesigns

**Comment by XceeDesigns** [comment]
Not required

**Pull request closed without merging**
