### PR TITLE
Map image top margin fixed and align with contact form

### PR DESCRIPTION
**Pull request by zalabhavy**
I just used bootstrap mt and ml command.
Here I give top margin , left margin to map image and align that with contact form for better look.
image

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Check out responsiveness for all device and after correction do let us know

**Comment by zalabhavy** [comment]
Works Fine....
For medium screen:

image

For small screen:

image

**Comment by zalabhavy** [comment]
@XceeDesigns Please Check it. It works fine.

**Comment by zalabhavy** [comment]
@ParthMadhvani2 please check it and merge !

**Comment by ParthMadhvani2** [comment]
Hi, @zalabhavy for small screen add padding/ margin on the right side
Screenshot 2024-06-03 at 12 43 43 PM

**Pull request closed without merging**
