### PR TITLE
custom cursor added 

### PR DESCRIPTION
**Pull request by chaanakyaaM**
The custom cursor for the website is added .

This feature closes issue #189 

Once review the PR and let me know if there are any changes to be made.
Thank you.

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Not looking good @chaanakyaaM

**Comment by chaanakyaaM** [comment]
ok i will change it.

**Comment by chaanakyaaM** [comment]
https://github.com/XceeDesigns/Website/assets/131477601/fd8aedc3-4fe8-4cf6-93a0-136b113a3730

Do you like this effect?

If you want i will remove the cursor, so that it looks like the black dot is the cursor(the color of the black dot can also be changed, as per your requirements).

**Comment by XceeDesigns** [comment]
Make it grey and with lighter tone and all set @chaanakyaaM

**Comment by chaanakyaaM** [comment]
sure.

**Pull request closed without merging**
