### PR TITLE
enhancement: Update background images and styles in style.css

### PR DESCRIPTION
**Pull request by haard18**
Fixed issue #81 with proffesional images
1. responsive design is provided with all sizes including their pixel size
image

2. Powerful performance is changed into a core processor depicting the actual execution engine behind algorithms
image

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Can you change second image.
Use image with settle colors.

**Comment by XceeDesigns** [comment]
Kindly again review second image we need some backgroundless images refer your first image.

**Comment by haard18** [comment]
Okay Will DO!

**Comment by XceeDesigns** [comment]
Time limit exceeded

**Pull request closed without merging**
