### PR TITLE
fixed newletter  issue #9

### PR DESCRIPTION
**Pull request by kairveeehh**
#9  as said I have aligned teh UI with the site's theme and added responsiveness across all the devices 
@XceeDesigns please review it sooner or give an update about it 
## @XceeDesigns please review and merge it :)
Screenshot 2024-05-11 192251
Screenshot 2024-05-11 192941

### CODE REVIEW

**Comment by kairveeehh** [comment]
I closed the wrong PR by mistake , it is now open to be reviewed and merged @XceeDesigns

**Comment by kairveeehh** [comment]
any updates ? @XceeDesigns  please review and merge it

**Comment by kairveeehh** [comment]
@XceeDesigns  its been long since I fixed this issue made it responsive too and adjusted the theme as well , please review and merge it  
@XceeDesigns

**Comment by XceeDesigns** [comment]
@kairveeehh we understand and praise your efforts but our inhouse developers are not satisfied by your proposed designs.
Hope you understand, will love if you want to work on another issue.

Happy Coding!

**Comment by kairveeehh** [comment]
unprofessional organization

**Pull request closed without merging**
