### PR TITLE
Fixed added autofocused to the input field

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I added the autofocus to the input search filed when user clicks on the search icon the input will comes will already focused .

closes : #146 

https://github.com/XceeDesigns/Website/assets/118350936/4a9e733c-b43b-4457-a45a-565812988840

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
Hii @XceeDesigns  can you please review it

**Comment by Ayushmaanagarwal1211** [comment]
Hii @XceeDesigns  please review this pr

**Comment by Ayushmaanagarwal1211** [comment]
Oh i forgot actually i  also solved #157  of level 2 tag i.e adding about us page that's why about page i their i created whole new about page for the website

**Comment by ParthMadhvani2** [comment]
@Ayushmaanagarwal1211 can you open the pull request for the About page again as there are many errors 
I would merge this issue related to the code

**Review by ParthMadhvani2 — APPROVED** [review]

**Comment by Ayushmaanagarwal1211** [comment]
Ya sure

**Comment by ParthMadhvani2** [comment]
@Ayushmaanagarwal1211 Two changes are there
1. On the home page about us is in lowercase
2. On About page in the footer the link is not attached

**Review by ParthMadhvani2 — CHANGES_REQUESTED** [review]
Change it to uppercase don't remove it

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am working on it first i raise pr for autofocused and then for about us please wait 15min

**Comment by Ayushmaanagarwal1211** [comment]
@ParthMadhvani2  i fixed it but can you please tell about which link are you talking in footer i am not understanding after this i will make pr

**Comment by ParthMadhvani2** [comment]
@Ayushmaanagarwal1211 first make a pr for auto focus

**Comment by ParthMadhvani2** [comment]
@Ayushmaanagarwal1211 ok

**Pull request closed without merging**
