### PR TITLE
ABOUT US PAGE READY

### PR DESCRIPTION
**Pull request by NitinChakrawarti**
I have created  a about us page for website which matches with theme of website and responsive also.
My issue no. #68

**Currently website doesn't have any about us page.**

Screenshot 2024-05-14 203856

### **After creating about us page** 

https://github.com/XceeDe/Website/assets/149225785/cea0b2ef-1917-4daa-996a-c0644cec49c4

@XceeDesigns  please assign this PR to me and respective label in it

### CODE REVIEW

**Comment by XceeDesigns** [comment]
It makes website redundent!
Try something unique but dont simply copy and paste

**Comment by NitinChakrawarti** [comment]
> It makes website redundent! Try something unique but dont simply copy and paste

Okay , This time I will try something new

**Comment by NitinChakrawarti** [comment]
> It makes website redundent! Try something unique but dont simply copy and paste

If you can give some hints regarding what kind of things you need in about section, it will be better for me to implement specially those things in website.

**Comment by XceeDesigns** [comment]
Connect with me on discord for more info

**Comment by XceeDesigns** [comment]
Not required

**Pull request closed without merging**
