### PR TITLE
fixed twitter logo in the footer section

### PR DESCRIPTION
**Pull request by YadlaMani**
image

### CODE REVIEW

**Comment by YadlaMani** [comment]
#75 fixiing this issue

**Comment by XceeDesigns** [comment]
Kindly fix same issue for other pages as well.

**Comment by YadlaMani** [comment]
@XceeDesigns can you pls mention the pages with this issue if possible
i can work faster that way!

**Comment by XceeDesigns** [comment]
Pages involved :
1. services.html
2. contact-dashboard.html
3. contact.html
4. 404.html
5. maintenance.html

**Comment by YadlaMani** [comment]
@XceeDesigns and if possible  can you increase the level of the issue in gssoc'24

**Comment by YadlaMani** [comment]
#77

**Comment by XceeDesigns** [comment]
Approved!
upgraded label from level1 to level2.

Happy Coding!

**Comment by YadlaMani** [comment]
@XceeDesigns thank you is there any other issue I can work on no one working?

**Pull request merged**
