### PR TITLE
New Custom Cursor added (issue: #189)

### PR DESCRIPTION
**Pull request by chaanakyaaM**
Closes issue: #189 

https://github.com/XceeDesigns/Website/assets/131477601/589b3211-fdad-42d0-bfc7-40eb1593417e

### CODE REVIEW

**Comment by chaanakyaaM** [comment]
Let me know if there are any changes to be made.

**Comment by chaanakyaaM** [comment]
@XceeDesigns  please review this PR.

**Comment by chaanakyaaM** [comment]
@XceeDesigns  let me know if there are any changes to be made

**Comment by chaanakyaaM** [comment]
please review this PR.

**Comment by chaanakyaaM** [comment]
@XceeDesigns  let me know if there are any changes to be made.

**Comment by chaanakyaaM** [comment]
@Ayushmaanagarwal1211  please review this PR and let me know it there are any changes to be made.

**Comment by Ayushmaanagarwal1211** [comment]
> @Ayushmaanagarwal1211 please review this PR and let me know it there are any changes to be made.

@chaanakyaaM  I am not a reviewer for this repo maybe you typed wrong

**Comment by chaanakyaaM** [comment]
apologies

**Pull request closed without merging**
