### PR TITLE
contact page updated

### PR DESCRIPTION
**Pull request by harinisayani**
I have updated the contact page again.
Once please check it.
Screenshot (150)

### CODE REVIEW

**Comment by XceeDesigns** [comment]
Check out phone view and correct it
image

And align map with contact us division and add light box-shadow

**Comment by harinisayani** [comment]
I have updated contact page.
Once please check it.
Screenshot (153)

**Comment by ParthMadhvani2** [comment]
@harinisayani do not change the format of the contact form 
you have to align the map

**Comment by harinisayani** [comment]
Ok, can I give same border and box shadow to map. 
And leave contact page as it is.

**Pull request closed without merging**
